using System;
using System.Collections.Generic;
using System.Text;

namespace Website.Models
{
    public class BusinessType
    {
        /**
        *
        * This field was generated by MyBatis Generator.
        * This field corresponds to the database column BusinessType.BusinessID
        *
        * @mbg.generated
        */
        public int businessid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column BusinessType.BusinessDes
         *
         * @mbg.generated
         */
        public string businessdes { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column BusinessType.SortNum
         *
         * @mbg.generated
         */
        public short sortnum { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column BusinessType.IsShow
         *
         * @mbg.generated
         */
        public short isshow { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column BusinessType.Icon
         *
         * @mbg.generated
         */
        public string icon { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column BusinessType.LargeIcon
         *
         * @mbg.generated
         */
        public string largeicon { get; set; }
    }
}
