using System;
using System.Collections.Generic;
using System.Text;

namespace Website.Models
{
    public class PublisherInfo
    {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column PublisherInfo.ShopID
         *
         * @mbg.generated
         */
        public long shopid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column PublisherInfo.UserName
         *
         * @mbg.generated
         */
        public string username { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column PublisherInfo.UserMobile
         *
         * @mbg.generated
         */
        public string usermobile { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column PublisherInfo.MobilePic
         *
         * @mbg.generated
         */
        public string mobilepic { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column PublisherInfo.CreateTime
         *
         * @mbg.generated
         */
        public DateTime createtime { get; set; }
    }
}
