using System;
using System.Collections.Generic;
using System.Text;

namespace Website.Models
{
    public class ShopPic
    {
        /**
        *
        * This field was generated by MyBatis Generator.
        * This field corresponds to the database column ShopPic.PicID
        *
        * @mbg.generated
        */
        public long picid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopPic.ShopID
         *
         * @mbg.generated
         */
        public long shopid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopPic.PicUrl
         *
         * @mbg.generated
         */
        public string picurl { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopPic.CreateTime
         *
         * @mbg.generated
         */
        public DateTime createtime { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopPic.IsActive
         *
         * @mbg.generated
         */
        public short isactive { get; set; }
    }
}
