using System;
using System.Collections.Generic;
using System.Text;

namespace Website.Models
{
    public class ShopInfo
    {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.ShopID
         *
         * @mbg.generated
         */
        public long shopid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.ShopTilte
         *
         * @mbg.generated
         */
        public string shoptilte { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.ShopPrice
         *
         * @mbg.generated
         */
        public double shopprice { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.ShopArea
         *
         * @mbg.generated
         */
        public int shoparea { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.ShopDisc
         *
         * @mbg.generated
         */
        public string shopdisc { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.BusinessID
         *
         * @mbg.generated
         */
        public int businessid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.CityName
         *
         * @mbg.generated
         */
        public string cityname { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.AreaName
         *
         * @mbg.generated
         */
        public string areaname { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.BurgName
         *
         * @mbg.generated
         */
        public string burgname { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.SourceID
         *
         * @mbg.generated
         */
        public int sourceid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.PublishTime
         *
         * @mbg.generated
         */
        private DateTime publishtime { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.ModifyStatus
         *
         * @mbg.generated
         */
        public short modifystatus { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.CreateTime
         *
         * @mbg.generated
         */
        public DateTime createtime { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.UpdateTime
         *
         * @mbg.generated
         */
        private DateTime updatetime { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.IsActive
         *
         * @mbg.generated
         */
        public short isactive { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopInfo.IsActive
         *
         * @mbg.generated
         */
        public PublisherInfo publisherInfo { get; set; }
    }
}
