using System;
using System.Collections.Generic;
using System.Text;

namespace Website.Models
{
    public class ShopDetail
    {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopDetail.DetailID
         *
         * @mbg.generated
         */
        public long detailid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopDetail.ShopID
         *
         * @mbg.generated
         */
        public long shopid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopDetail.Info
         *
         * @mbg.generated
         */
        public string info { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopDetail.CreateTime
         *
         * @mbg.generated
         */
        public DateTime createtime { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column ShopDetail.IsActive
         *
         * @mbg.generated
         */
        public short isactive { get; set; }
    }
}
