using System;
using System.Collections.Generic;
using System.Text;

namespace Website.Models
{
    public class UserAccount
    {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserAccount.UserID
         *
         * @mbg.generated
         */
        public int userid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserAccount.UserName
         *
         * @mbg.generated
         */
        public String username { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserAccount.OpenID
         *
         * @mbg.generated
         */
        public String openid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserAccount.Password
         *
         * @mbg.generated
         */
        public String password { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserAccount.Mobile
         *
         * @mbg.generated
         */
        public String mobile { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserAccount.LastLoginTime
         *
         * @mbg.generated
         */
        public String lastlogintime { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserAccount.CreateTime
         *
         * @mbg.generated
         */
        public String createtime { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserAccount.UpdateTime
         *
         * @mbg.generated
         */
        public String updatetime { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserAccount.IsActive
         *
         * @mbg.generated
         */
        public short isactive { get; set; }
    }
}
