using System;
using System.Collections.Generic;
using System.Text;

namespace Website.Models
{
    public class UserShopRela
    {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserShopRela.RelaID
         *
         * @mbg.generated
         */
        public int relaid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserShopRela.UserID
         *
         * @mbg.generated
         */
        public int userid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserShopRela.ShopID
         *
         * @mbg.generated
         */
        public int shopid { get; set; }

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserShopRela.CreateTime
         *
         * @mbg.generated
         */
        public String createtime;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserShopRela.IsActive
         *
         * @mbg.generated
         */
        public short isactive;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column UserShopRela.IsActive
         *
         * @mbg.generated
         */
        public ShopInfo shopInfo;
    }
}
